2014/07/09 15:20:06 [error] [exception.CException] exception 'CException' with message 'Property "MainController.site_title" is not defined.' in C:\OpenServer\domains\_GIT\erp\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\protected\views\layouts\main_layout.php(12): CComponent->__get('site_title')
#1 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(784): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\_GIT\erp\protected\controllers\MainController.php(9): CController->render('welcome')
#5 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): MainController->actionIndex()
#6 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('index')
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('main/index')
#11 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/
---
2014/07/09 15:21:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://erpgit.loc/
---
2014/07/09 15:22:36 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery-1.10.2.js".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery-1.10....')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery-1.10.2.js
HTTP_REFERER=http://erpgit.loc/main/login
---
2014/07/09 15:22:42 [error] [exception.CException] exception 'CException' with message 'Property "LoginForm.rememberMe" is not defined.' in C:\OpenServer\domains\_GIT\erp\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\protected\models\LoginForm.php(74): CComponent->__get('rememberMe')
#1 C:\OpenServer\domains\_GIT\erp\protected\controllers\MainController.php(39): LoginForm->login()
#2 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#3 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('login')
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('main/login')
#8 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/main/login
HTTP_REFERER=http://erpgit.loc/main/login
---
2014/07/09 15:22:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/09 15:24:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery-1.10.2.js".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery-1.10....')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery-1.10.2.js
HTTP_REFERER=http://erpgit.loc/main/login
---
2014/07/09 15:24:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/09 15:32:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/09 15:34:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://erpgit.loc/main/login
---
2014/07/09 15:34:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "js/jquery.min.map".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('js/jquery.min.m...')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/js/jquery.min.map
HTTP_REFERER=http://erpgit.loc/main/login
---
2014/07/09 15:38:24 [error] [php] include(Debug.php) [<a href='function.include'>function.include</a>]: failed to open stream: No such file or directory (C:\OpenServer\domains\_GIT\erp\framework\YiiBase.php:427)
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\protected\views\main\login.php(3): spl_autoload_call()
#1 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(126): require()
#2 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(95): MainController->renderInternal()
#3 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(869): MainController->renderFile()
#4 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(782): MainController->renderPartial()
#5 C:\OpenServer\domains\_GIT\erp\protected\controllers\MainController.php(54): MainController->render()
#6 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams()
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): MainController->runAction()
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): MainController->runActionWithFilters()
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): MainController->run()
#11 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController()
#12 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\OpenServer\domains\_GIT\erp\index.php(13): CWebApplication->run()
REQUEST_URI=/main/login
in C:\OpenServer\domains\_GIT\erp\protected\views\main\login.php (3)
in C:\OpenServer\domains\_GIT\erp\protected\controllers\MainController.php (54)
in C:\OpenServer\domains\_GIT\erp\index.php (13)
2014/07/09 15:42:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "products/index".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('products/index')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/products
HTTP_REFERER=http://erpgit.loc/main
---
2014/07/09 15:42:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "contractors/index".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('contractors/ind...')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/contractors
HTTP_REFERER=http://erpgit.loc/main
---
2014/07/09 15:42:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "employees/index".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('employees/index')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/employees
HTTP_REFERER=http://erpgit.loc/main
---
2014/07/09 16:48:37 [error] [exception.CException] exception 'CException' with message 'Object configuration must be an array containing a "class" element.' in C:\OpenServer\domains\_GIT\erp\framework\YiiBase.php:193
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#1 C:\OpenServer\domains\_GIT\erp\framework\gii\generators\model\ModelGenerator.php(17): CModule->getComponent('labels')
#2 [internal function]: ModelGenerator->actionGetTableNames('labels')
#3 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ModelGenerator), Array)
#4 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ModelGenerator), Object(ReflectionMethod), Array)
#5 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('getTableNames')
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/getTa...')
#10 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/gii/model/getTableNames?db=labels
HTTP_REFERER=http://erpgit.loc/gii/model/index
---
2014/07/09 16:48:45 [error] [exception.CException] exception 'CException' with message 'Object configuration must be an array containing a "class" element.' in C:\OpenServer\domains\_GIT\erp\framework\YiiBase.php:193
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#1 C:\OpenServer\domains\_GIT\erp\framework\gii\generators\model\ModelCode.php(428): CModule->getComponent('labels')
#2 C:\OpenServer\domains\_GIT\erp\framework\validators\CInlineValidator.php(42): ModelCode->validateConnectionId('connectionId', Array)
#3 C:\OpenServer\domains\_GIT\erp\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(ModelCode), 'connectionId')
#4 C:\OpenServer\domains\_GIT\erp\framework\base\CModel.php(159): CValidator->validate(Object(ModelCode), NULL)
#5 C:\OpenServer\domains\_GIT\erp\framework\gii\CCodeGenerator.php(159): CModel->validate()
#6 C:\OpenServer\domains\_GIT\erp\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gii/model/index
HTTP_REFERER=http://erpgit.loc/gii/model/index
---
2014/07/09 16:51:38 [error] [exception.CException] exception 'CException' with message 'Object configuration must be an array containing a "class" element.' in C:\OpenServer\domains\_GIT\erp\framework\YiiBase.php:193
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#1 C:\OpenServer\domains\_GIT\erp\framework\gii\generators\model\ModelGenerator.php(17): CModule->getComponent('labels')
#2 [internal function]: ModelGenerator->actionGetTableNames('labels')
#3 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(ModelGenerator), Array)
#4 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(ModelGenerator), Object(ReflectionMethod), Array)
#5 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('getTableNames')
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/getTa...')
#10 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/gii/model/getTableNames?db=labels
HTTP_REFERER=http://erpgit.loc/gii/model/index
---
2014/07/09 16:51:48 [error] [exception.CException] exception 'CException' with message 'Object configuration must be an array containing a "class" element.' in C:\OpenServer\domains\_GIT\erp\framework\YiiBase.php:193
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\base\CModule.php(386): YiiBase::createComponent(Array)
#1 C:\OpenServer\domains\_GIT\erp\framework\gii\generators\model\ModelCode.php(428): CModule->getComponent('labels')
#2 C:\OpenServer\domains\_GIT\erp\framework\validators\CInlineValidator.php(42): ModelCode->validateConnectionId('connectionId', Array)
#3 C:\OpenServer\domains\_GIT\erp\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(ModelCode), 'connectionId')
#4 C:\OpenServer\domains\_GIT\erp\framework\base\CModel.php(159): CValidator->validate(Object(ModelCode), NULL)
#5 C:\OpenServer\domains\_GIT\erp\framework\gii\CCodeGenerator.php(159): CModel->validate()
#6 C:\OpenServer\domains\_GIT\erp\framework\gii\CCodeGenerator.php(63): CCodeGenerator->prepare()
#7 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): CCodeGenerator->actionIndex()
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('index')
#12 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#13 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/gii/model/index
HTTP_REFERER=http://erpgit.loc/gii/model/index
---
2014/07/09 16:59:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/09 17:15:06 [error] [exception.CException] exception 'CException' with message 'Property "MainController.labels" is not defined.' in C:\OpenServer\domains\_GIT\erp\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\protected\views\main\login.php(8): CComponent->__get('labels')
#1 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#5 C:\OpenServer\domains\_GIT\erp\protected\controllers\MainController.php(54): CController->render('login', Array)
#6 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('main/login')
#12 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/main/login
---
2014/07/09 17:20:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "products/index".' in C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('products/index')
#1 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/products
HTTP_REFERER=http://erpgit.loc/main
---
2014/07/09 17:56:29 [error] [exception.CException] exception 'CException' with message 'Property "ProductsController.sub_menu" is not defined.' in C:\OpenServer\domains\_GIT\erp\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\protected\views\products\list_categories.php(9): CComponent->__get('sub_menu')
#1 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(782): CController->renderPartial('list_categories', Array, true)
#5 C:\OpenServer\domains\_GIT\erp\protected\controllers\ProductsController.php(35): CController->render('list_categories', Array)
#6 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): ProductsController->actionCategories()
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('categories')
#11 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('products/catego...')
#12 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/products/categories
HTTP_REFERER=http://erpgit.loc/main
---
2014/07/09 17:56:53 [error] [exception.CException] exception 'CException' with message 'Property "ProductsController.sub_menu" is not defined.' in C:\OpenServer\domains\_GIT\erp\framework\base\CComponent.php:130
Stack trace:
#0 C:\OpenServer\domains\_GIT\erp\protected\views\products\list_categories.php(9): CComponent->__get('sub_menu')
#1 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#2 C:\OpenServer\domains\_GIT\erp\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#3 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#4 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(782): CController->renderPartial('list_categories', Array, true)
#5 C:\OpenServer\domains\_GIT\erp\protected\controllers\ProductsController.php(35): CController->render('list_categories', Array)
#6 C:\OpenServer\domains\_GIT\erp\framework\web\actions\CInlineAction.php(49): ProductsController->actionCategories()
#7 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\OpenServer\domains\_GIT\erp\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(282): CController->run('categories')
#11 C:\OpenServer\domains\_GIT\erp\framework\web\CWebApplication.php(141): CWebApplication->runController('products/catego...')
#12 C:\OpenServer\domains\_GIT\erp\framework\base\CApplication.php(180): CWebApplication->processRequest()
#13 C:\OpenServer\domains\_GIT\erp\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/products/categories
HTTP_REFERER=http://erpgit.loc/main
---
2014/07/09 18:54:25 [error] [php] Non-static method Debug::d() should not be called statically (C:\OpenServer\domains\yerp.local\protected\helpers\Label.php:14)
Stack trace:
#0 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(126): require()
#1 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(95): MainController->renderInternal()
#2 C:\OpenServer\domains\yerp.local\framework\web\CController.php(869): MainController->renderFile()
#3 C:\OpenServer\domains\yerp.local\framework\web\CController.php(782): MainController->renderPartial()
#4 C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php(54): MainController->render()
#5 C:\OpenServer\domains\yerp.local\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#6 C:\OpenServer\domains\yerp.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#7 C:\OpenServer\domains\yerp.local\framework\web\CController.php(286): MainController->runAction()
#8 C:\OpenServer\domains\yerp.local\framework\web\CController.php(265): MainController->runActionWithFilters()
#9 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(282): MainController->run()
#10 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#11 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\OpenServer\domains\yerp.local\index.php(13): CWebApplication->run()
REQUEST_URI=/main/login
in C:\OpenServer\domains\yerp.local\protected\helpers\Label.php (14)
in C:\OpenServer\domains\yerp.local\protected\helpers\Label.php (14)
in C:\OpenServer\domains\yerp.local\protected\views\main\login.php (8)
2014/07/09 18:54:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\OpenServer\domains\yerp.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2014/07/09 18:57:21 [error] [php] Missing argument 1 for CActiveRecord::getAttribute(), called in C:\OpenServer\domains\yerp.local\framework\base\CComponent.php on line 111 and defined (C:\OpenServer\domains\yerp.local\framework\db\ar\CActiveRecord.php:691)
Stack trace:
#0 C:\OpenServer\domains\yerp.local\protected\helpers\Label.php(14): Labels->__get()
#1 C:\OpenServer\domains\yerp.local\protected\views\main\login.php(8): Get()
#2 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(126): require()
#3 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(95): MainController->renderInternal()
#4 C:\OpenServer\domains\yerp.local\framework\web\CController.php(869): MainController->renderFile()
#5 C:\OpenServer\domains\yerp.local\framework\web\CController.php(782): MainController->renderPartial()
#6 C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php(54): MainController->render()
#7 C:\OpenServer\domains\yerp.local\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#8 C:\OpenServer\domains\yerp.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\yerp.local\framework\web\CController.php(286): MainController->runAction()
#10 C:\OpenServer\domains\yerp.local\framework\web\CController.php(265): MainController->runActionWithFilters()
#11 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(282): MainController->run()
#12 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\yerp.local\index.php(13): CWebApplication->run()
REQUEST_URI=/main/login
in C:\OpenServer\domains\yerp.local\protected\helpers\Label.php (14)
in C:\OpenServer\domains\yerp.local\protected\views\main\login.php (8)
in C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php (54)
2014/07/09 19:12:49 [error] [exception.CDbException] exception 'CDbException' with message 'The DB query must contain the "from" portion.' in C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php:566
Stack trace:
#0 C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php(160): CDbCommand->buildQuery(Array)
#1 C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php(484): CDbCommand->getText()
#2 C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#3 C:\OpenServer\domains\yerp.local\protected\helpers\Label.php(17): CDbCommand->queryAll()
#4 C:\OpenServer\domains\yerp.local\protected\views\main\login.php(8): Label::Get('enter password')
#5 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#6 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#7 C:\OpenServer\domains\yerp.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#8 C:\OpenServer\domains\yerp.local\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#9 C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php(54): CController->render('login', Array)
#10 C:\OpenServer\domains\yerp.local\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#11 C:\OpenServer\domains\yerp.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\OpenServer\domains\yerp.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\OpenServer\domains\yerp.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/login')
#16 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 C:\OpenServer\domains\yerp.local\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/main/login
---
2014/07/09 19:18:16 [error] [php] array_merge() [<a href='function.array-merge'>function.array-merge</a>]: Argument #2 is not an array (C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php:472)
Stack trace:
#0 C:\OpenServer\domains\yerp.local\protected\helpers\Label.php(18): CDbCommand->queryColumn()
#1 C:\OpenServer\domains\yerp.local\protected\views\main\login.php(8): Get()
#2 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(126): require()
#3 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(95): MainController->renderInternal()
#4 C:\OpenServer\domains\yerp.local\framework\web\CController.php(869): MainController->renderFile()
#5 C:\OpenServer\domains\yerp.local\framework\web\CController.php(782): MainController->renderPartial()
#6 C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php(54): MainController->render()
#7 C:\OpenServer\domains\yerp.local\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#8 C:\OpenServer\domains\yerp.local\framework\web\CController.php(308): CInlineAction->runWithParams()
#9 C:\OpenServer\domains\yerp.local\framework\web\CController.php(286): MainController->runAction()
#10 C:\OpenServer\domains\yerp.local\framework\web\CController.php(265): MainController->runActionWithFilters()
#11 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(282): MainController->run()
#12 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController()
#13 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 C:\OpenServer\domains\yerp.local\index.php(13): CWebApplication->run()
REQUEST_URI=/main/login
in C:\OpenServer\domains\yerp.local\protected\helpers\Label.php (18)
in C:\OpenServer\domains\yerp.local\protected\views\main\login.php (8)
in C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php (54)
2014/07/09 19:19:02 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[HY000]: General error: 25 bind or column index out of range. The SQL statement executed was: SELECT *
FROM 'labels'
GROUP BY "label", "value".
in C:\OpenServer\domains\yerp.local\protected\helpers\Label.php (18)
in C:\OpenServer\domains\yerp.local\protected\views\main\login.php (8)
in C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php (54)
2014/07/09 19:19:02 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 25 bind or column index out of range. The SQL statement executed was: SELECT *
FROM 'labels'
GROUP BY "label", "value"' in C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php(455): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\yerp.local\protected\helpers\Label.php(18): CDbCommand->queryColumn(Array)
#2 C:\OpenServer\domains\yerp.local\protected\views\main\login.php(8): Label::Get('enter password')
#3 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#4 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\yerp.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#6 C:\OpenServer\domains\yerp.local\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#7 C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php(54): CController->render('login', Array)
#8 C:\OpenServer\domains\yerp.local\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#9 C:\OpenServer\domains\yerp.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\yerp.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\yerp.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/login')
#14 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\yerp.local\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/main/login
---
2014/07/09 19:19:42 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[HY000]: General error: 25 bind or column index out of range. The SQL statement executed was: SELECT "labels", "value"
FROM 'labels'
GROUP BY "label", "value".
in C:\OpenServer\domains\yerp.local\protected\helpers\Label.php (18)
in C:\OpenServer\domains\yerp.local\protected\views\main\login.php (8)
in C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php (54)
2014/07/09 19:19:42 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 25 bind or column index out of range. The SQL statement executed was: SELECT "labels", "value"
FROM 'labels'
GROUP BY "label", "value"' in C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\OpenServer\domains\yerp.local\framework\db\CDbCommand.php(455): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 C:\OpenServer\domains\yerp.local\protected\helpers\Label.php(18): CDbCommand->queryColumn(Array)
#2 C:\OpenServer\domains\yerp.local\protected\views\main\login.php(8): Label::Get('enter password')
#3 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(126): require('C:\OpenServer\d...')
#4 C:\OpenServer\domains\yerp.local\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\OpenServer\d...', Array, true)
#5 C:\OpenServer\domains\yerp.local\framework\web\CController.php(869): CBaseController->renderFile('C:\OpenServer\d...', Array, true)
#6 C:\OpenServer\domains\yerp.local\framework\web\CController.php(782): CController->renderPartial('login', Array, true)
#7 C:\OpenServer\domains\yerp.local\protected\controllers\MainController.php(54): CController->render('login', Array)
#8 C:\OpenServer\domains\yerp.local\framework\web\actions\CInlineAction.php(49): MainController->actionLogin()
#9 C:\OpenServer\domains\yerp.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 C:\OpenServer\domains\yerp.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 C:\OpenServer\domains\yerp.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(282): CController->run('login')
#13 C:\OpenServer\domains\yerp.local\framework\web\CWebApplication.php(141): CWebApplication->runController('main/login')
#14 C:\OpenServer\domains\yerp.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 C:\OpenServer\domains\yerp.local\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/main/login
---
